services:
  spireAgent:
    image: ghcr.io/spiffe/spire-agent:1.14.1
    container_name: dts-edge-spire-agent
    environment:
      - SPIRE_SOCKET_PATH=/run/spire/sockets/agent.sock
      - TZ=Asia/Tokyo
    volumes:
      - ./spireAgent/conf/agent.conf:/opt/spire/conf/agent/agent.conf:ro
      - /opt/otmc/spiffe/data:/run/spire/data
      - /opt/otmc/spiffe/svids:/run/spire/svids
      - /opt/otmc/spiffe/certs:/run/spire/certs
    restart: unless-stopped
    network_mode : "host"
