services:
  spire-agenth-helper:
    build: ./spiffeImage
    container_name: dts-edge-spire-agent-helper
    environment:
      - SPIRE_SOCKET_PATH=/run/spire/sockets/agent.sock
      - TZ=Asia/Tokyo
    volumes:
      - ./spireAgent/conf/agent.conf:/opt/spire/conf/agent/agent.conf:ro
      - ./spiffeHelper/conf/helper-config.conf:/etc/helper-config.conf:ro
      - /opt/otmc/spiffe/data:/run/spire/data
      - /opt/otmc/spiffe/svids:/run/spire/svids
      - /opt/otmc/spiffe/certs:/run/spire/certs
      - /opt/otmc/spiffe/sockets:/run/spire/sockets
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 64M
        reservations:
          memory: 32M 
  rclone:
    build: ./rcloneImage
    container_name: dts-edge-rclone
    environment:
      - SPIRE_SOCKET_PATH=/run/spire/sockets/agent.sock
      - TZ=Asia/Tokyo
    volumes:
      - /opt/otmc/spiffe/svids:/run/spire/svids
      - ./syncStorage:/syncStorage
    working_dir: /syncStorage
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 64M
        reservations:
          memory: 32M 