server {
  bind_address = "0.0.0.0"
  bind_port    = "8081"
  trust_domain = "wator.xyz"
  data_dir     = "/run/spire/data"
  log_level    = "INFO"
}
plugins {
  DataStore "sql" {
    plugin_data {
      database_type = "sqlite3"
      connection_string = "file:/run/spire/data/sqlite3.db?cache=shared&_journal=WAL"
    }
  }

  KeyManager "disk" {
    plugin_data {
      keys_path = "/run/spire/data/keys"
    }
  }

  NodeAttestor "join_token" {
    plugin_data {}
  }

  UpstreamAuthority "disk" {
    plugin_data {
      key_file_path  = "/run/spire/ca/ca.key"
      cert_file_path = "/run/spire/ca/ca.crt"
    }
  }
}
