agent {
    trust_domain        = "spiffe.wator.xyz"
    data_dir            = "/run/spire/data"
    server_address      = "spiffe.wator.xyz"
    server_port         = "38081"
    socket_path         = "/run/spire/sockets/agent.sock"
    log_level           = "DEBUG"
    trust_bundle_path   = "/run/spire/certs/spiffe-ca-bundle.pem"
}
plugins {   
    NodeAttestor "x509pop" {
        plugin_data {
            certificate_path = "/run/spire/certs/x509pop-agent-leaf.crt"
            private_key_path = "/run/spire/certs/x509pop-agent-leaf.key"
        }
    }
    KeyManager "disk" {
        plugin_data {
            directory = "/run/spire/data"
        }
    }    
    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
