services:
  spire-server:
    image: ghcr.io/spiffe/spire-server:1.14.1
    container_name: dts-cloudTwin-spire-server
    restart: unless-stopped
    ports:
      - "38081:8081"
    volumes:
      - ./conf/server.conf:/run/spire/config/server.conf:ro
      - ./conf/server.conf:/opt/spire/conf/server/server.conf:ro
      - /opt/otmc/spiffe/data:/run/spire/data
      - /opt/otmc/spiffe/ca:/run/spire/ca
    command: 
      - "spire-server"
      - "run"
      - "-config"
      - "/run/spire/config/server.conf"
