version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio-dts
      MINIO_ROOT_PASSWORD: dGhpc0lzQVRlc3QxMg
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
  coredns:
    image: coredns/coredns:1.12.4
    container_name: coredns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./Corefile:/etc/coredns/Corefile
    restart: unless-stopped
