services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/secure/dts/provision/factory/keys/server.priv.key:/etc/nginx/ssl/server.key:ro
      - /opt/secure/dts/provision/factory/ssl/server.crt:/etc/nginx/ssl/server.crt:ro
      - /opt/secure/dts/provision/factory/ssl/rootca.crt:/etc/nginx/ssl/rootca.crt:ro
      - /dev/shm/:/dev/shm/ 
