version: '3.8'
services:
  nginx:
    image: nginx:lts
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - node
    restart: unless-stopped
    networks:
      - app-network

  node:
    image: node:24
    container_name: node
    working_dir: /app
    volumes:
      - /opt/secure/dts/provision/factory:/secure/factory
      - /opt/secure/dts/provision/cloud:/secure/cloud
      - /opt/secure/dts/provision/enduser:/secure/enduser
      - ./node-app:/app
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
