agent_address = "/run/spire/sockets/agent.sock"
#cmd = "echo certificates updated"
#renew_signal = "SIGHUP"
cert_dir = "/run/spire/svids"
svid_file_name = "svid_bucket_cert.pem"
svid_key_file_name = "svid_bucket_key.pem"
svid_bundle_file_name = "svid_bundle.pem"
