agent_address = "/run/spire/sockets/agent.sock"
#cmd = "echo certificates updated"
#renew_signal = "SIGHUP"
cert_dir = "/run/spire/certs"
svid_file_name = "svid.pem"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "bundle.pem"
